app_id: 4dced903-d911-4954-a1c2-59486974fb4e
app_secret: 6a7fh-~CX~BESBED4ZT95fl5w2-_P_mchD
redirect: http://localhost:8000/tutorial/callback
scopes: openid profile offline_access user.read calendars.read
authority: https://login.microsoftonline.com/common
authorize_endpoint: /oauth2/v2.0/authorize
token_endpoint: /oauth2/v2.0/token